In [1]:
import pandas as pd
import numpy as np

In [2]:
fact = pd.read_csv(r"c:\Users\msi\Downloads\DS&AI\1.Python\cross-SQL-Pandas-Problems\fact.csv")
Product = pd.read_csv(r"c:\Users\msi\Downloads\DS&AI\1.Python\cross-SQL-Pandas-Problems\Product.csv")
Location = pd.read_csv(r"c:\Users\msi\Downloads\DS&AI\1.Python\cross-SQL-Pandas-Problems\Location.csv")

In [3]:
# factors = {COGS, budget profit, etc}
print(fact.shape)

fact.head()

(4248, 14)

,Date,ProductId,Profit,Sales,Margin,COGS,Total Expenses,Marketing,Inventory,Budget Profit,Budget COGS,Budget Margin,Budget Sales,Area Code
0,1/1/2010,1,94,219,130,89,36,24,777,100,90,130,220,719
1,1/1/2010,2,68,190,107,83,39,27,623,80,80,110,190,970
2,1/1/2010,3,101,234,139,95,38,26,821,110,100,140,240,970
3,1/1/2010,13,30,100,56,44,26,14,623,30,30,50,80,303
4,1/1/2010,5,54,134,80,54,26,15,456,70,60,90,150,303

In [5]:
print(Product.shape)
Product.head()

(13, 4)

   ProductId Product Type            Product     Type
0          1       Coffee           Amaretto  Regular
1          2       Coffee          Columbian  Regular
2          3       Coffee  Decaf Irish Cream    Decaf
3          4     Espresso        Caffe Latte  Regular
4          5     Espresso        Caffe Mocha  Regular

In [6]:
print(Location.shape)
Location.head()

(156, 4)

   Area Code        State Market   Market Size
0        203  Connecticut   East  Small Market
1        206   Washington   West  Small Market
2        209   California   West  Major Market
3        210        Texas  South  Major Market
4        212     New York   East  Major Market

In [7]:
#####1. Display the number of states present in the LocationTable.
L = Location['State'].unique()
print(f"The number of states present in Location table are {len(L)}, i.e:")
for i,state in enumerate(L,1):
    print(f"{i}. {state}")

The number of states present in Location table are 20, i.e:
1. Connecticut
2. Washington
3. California
4. Texas
5. New York
6. Ohio
7. Illinois
8. Louisiana
9. Florida
10. Wisconsin
11. Colorado
12. Missouri
13. Iowa
14. Massachusetts
15. Oklahoma
16. Utah
17. Oregon
18. New Mexico
19. New Hampshire
20. Nevada

In [8]:
#######2.How many products are of regular type?
P = Product[Product['Type'] == 'Regular']
print(f"{P.shape[0]} products are of regular type")

8 products are of regular type

In [3]:
#######3. How much spending has been done on marketing of product ID 1?
fact.head()
fact.columns
F = fact.groupby('ProductId')['Marketing'].sum().iloc[0]
print(f"{F} dollars has been spent on markering of product ID 1")

4658 dollars has been spent on markering of product ID 1

In [4]:
#######4. What is the minimum sales of a product?
fact.head()
min_sales_of_a_product = fact.groupby('ProductId')['Sales'].min().idxmin()
min_sales = fact['Sales']
print(f"The minimum sales of a product is {fact['Sales'].min()} for product ID {min_sales_of_a_product}")

The minimum sales of a product is 17 for product ID 13

In [11]:
####5. Display the max Cost of Good Sold (COGS)
print(f'The max COGS is {fact['COGS'].max()}')

The max COGS is 364

In [12]:
#####6. Display the deatils of Product type as coffee
Product.head()
P = Product[Product['Product Type'] == 'Coffee']
P

   ProductId Product Type            Product     Type
0          1       Coffee           Amaretto  Regular
1          2       Coffee          Columbian  Regular
2          3       Coffee  Decaf Irish Cream    Decaf

In [13]:
######7. Display the details where total expenses are greater than 40.
fact.head()
F = fact[fact['Total Expenses'] > 40]
F

,Date,ProductId,Profit,Sales,Margin,COGS,Total Expenses,Marketing,Inventory,Budget Profit,Budget COGS,Budget Margin,Budget Sales,Area Code
5,1/1/2010,6,53,180,108,72,55,23,558,80,80,130,210,720
6,1/1/2010,8,99,341,171,170,72,47,1091,110,140,160,300,970
7,1/1/2010,9,0,150,87,63,87,57,435,20,50,80,130,719
8,1/1/2010,10,33,140,80,60,47,19,336,40,50,70,120,970
9,1/1/2010,11,17,130,72,58,55,22,338,20,40,70,110,719
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4241,12/1/2011,8,156,308,174,115,69,37,1166,110,100,160,260,253
4244,12/1/2011,5,34,155,80,65,57,24,403,30,60,80,140,509
4245,12/1/2011,6,76,188,96,80,45,24,1079,60,70,100,170,360
4246,12/1/2011,2,86,188,104,72,46,23,461,80,80,120,200,360
4247,12/1/2011,3,30,266,145,105,125,95,716,50,120,170,290,206

In [14]:
######8. What is the average sales in area code 719?
fact.columns
F = fact[fact['Area Code'] == 719]['Sales'].mean()
print(f"The average sales in area code 719 is {F}")

The average sales in area code 719 is 186.58333333333334

In [6]:
#####9. Find out the total profit generated by Colorado state.
Location.head()
Location_fact = pd.merge(fact, Location, on='Area Code', how='left')
profit_colorado = Location_fact[Location_fact['State'] == 'Colorado']['Profit'].sum()
print(f"The total profit generated by Colorado state is {profit_colorado}")

The total profit generated by Colorado state is 17743

In [16]:
######10. Display the average inventory for each product ID.
fact.head()
fact.groupby('ProductId')['Inventory'].mean()

ProductId
1      741.020833
2      707.550000
3      838.682292
4      255.990741
5      756.241667
6      755.205882
7      879.638889
8      712.645833
9      718.537500
10    1095.906250
11     737.833333
12     757.173611
13     900.375000
Name: Inventory, dtype: float64

In [13]:
####11. Display state in a sequential order in a Location Table.
L = Location.sort_values(by='State', ascending=True)
L= L['State'].unique()
L = pd.DataFrame(L)
L

                0
0      California
1        Colorado
2     Connecticut
3         Florida
4        Illinois
5            Iowa
6       Louisiana
7   Massachusetts
8        Missouri
9          Nevada
10  New Hampshire
11     New Mexico
12       New York
13           Ohio
14       Oklahoma
15         Oregon
16          Texas
17           Utah
18     Washington
19      Wisconsin

In [16]:
#####12. Display the average budget of the Product where the average budget
# margin should be greater than 100.

# F = fact[fact['Budget Margin'] > 100]
F1 = fact.groupby('ProductId')[['Budget Margin','Budget Sales']].mean()
F1 = F1[F1['Budget Margin'] > 100]
F1

           Budget Margin  Budget Sales
ProductId
2             173.208333    279.958333
6             107.990196    185.588235
7             182.222222    314.166667
8             100.208333    166.250000
12            103.680556    176.736111

In [19]:
#######13. What is the total sales done on date 2010-01-01?
fact.head()
fact['Date'].value_counts
F = fact[fact['Date'] == '1/1/2010']['Sales'].sum()
print(f"Total Sales done on 2010-01-01 is {F}")

Total Sales done on 2010-01-01 is 31555

In [17]:
###14. Display the average total expense of each product ID on an individual date.
F =fact.groupby(['Date','ProductId'])['Total Expenses'].mean()
F.sort_index(ascending = True)

Date      ProductId
1/1/2010  1            46.125000
          2            63.100000
          3            50.062500
          4            50.666667
          5            60.100000
                         ...
9/1/2011  9            58.600000
          10           52.250000
          11           45.062500
          12           60.500000
          13           47.166667
Name: Total Expenses, Length: 312, dtype: float64

In [19]:
###15. 15. Display the table with the following attributes such as date, productID,
###product_type, product, sales, profit, state, area_code.

fact.columns
Product.columns
F = fact[['Date', 'ProductId','Sales','Profit','Area Code']]
Location.columns
FnP= pd.merge(F,Product, on = 'ProductId', how= 'left')
FnPnL = pd.merge(FnP,Location, on='Area Code', how='left')
Table = FnPnL[['Date', 'ProductId','Product Type','Product','Sales','Profit','State','Area Code']]
Table

,Date,ProductId,Product Type,Product,Sales,Profit,State,Area Code
0,1/1/2010,1,Coffee,Amaretto,219,94,Colorado,719
1,1/1/2010,2,Coffee,Columbian,190,68,Colorado,970
2,1/1/2010,3,Coffee,Decaf Irish Cream,234,101,Colorado,970
3,1/1/2010,13,Tea,Green Tea,100,30,Colorado,303
4,1/1/2010,5,Espresso,Caffe Mocha,134,54,Colorado,303
...,...,...,...,...,...,...,...,...
4243,12/1/2011,4,Espresso,Caffe Latte,60,19,Washington,206
4244,12/1/2011,5,Espresso,Caffe Mocha,155,34,Washington,509
4245,12/1/2011,6,Espresso,Decaf Espresso,188,76,Washington,360
4246,12/1/2011,2,Coffee,Columbian,188,86,Washington,360
4247,12/1/2011,3,Coffee,Decaf Irish Cream,266,30,Washington,206

In [22]:
####16. Display the rank without any gap to show the sales wise rank.
# T = Table.groupby(['State'])['Sales'].sum().sort_values(ascending = False)
fact = fact.sort_values(by='Sales', ascending=False, ignore_index = True)
fact['Sales Rank'] = range(1, len(fact) + 1)
T = fact[['Sales Rank', 'ProductId', 'Sales']]
T.head(10)

   Sales Rank  ProductId  Sales
0           1          2    912
1           2          2    912
2           3          2    910
3           4          2    910
4           5          2    904
5           6          2    904
6           7          2    902
7           8          2    902
8           9          2    890
9          10          2    890

In [23]:
###17.17. Find the state wise profit and sales.
T = Table.groupby(['State'])[['Profit','Sales']].sum().sort_values(by = 'Profit', ascending=False)
T

               Profit  Sales
State
California      31785  96892
Illinois        30821  69883
Iowa            22212  54750
New York        20096  70852
Colorado        17743  48179
Massachusetts   16442  29965
Texas           15766  37410
Oregon          12439  40899
Florida         12310  37443
Washington      11405  38930
Ohio            10773  34517
Nevada          10616  60159
Wisconsin        8702  33069
Oklahoma         8558  27463
Utah             7751  35384
Connecticut      7621  25429
Louisiana        7355  23161
Missouri         3601  24647
New Hampshire    2748  14887
New Mexico        799  15892

In [24]:
####18. Find the state wise profit and sales along with the product name.
Table['Product Type'].value_counts()
T = Table.groupby(['State','Product Type'])[['Profit','Sales']].sum().sort_values(by = 'Profit', ascending=False)
T.head(10)

                            Profit  Sales
State         Product Type
Massachusetts Coffee         12489  13301
California    Espresso       11963  34299
Illinois      Espresso       11069  26608
California    Herbal Tea     10257  22721
Iowa          Tea            10111  26450
              Herbal Tea     10043  22058
New York      Tea             8984  17380
Nevada        Herbal Tea      8699  25752
New York      Coffee          8565  18245
Illinois      Herbal Tea      8227  16547

In [ ]:
####19. If there is an increase in sales of 5%, calculate the increased sales.

Table['Increased Sales'] = 0.05 * Table['Sales'] + Table['Sales'] 
Table.head()

C:\Users\msi\AppData\Local\Temp\ipykernel_1260\1157430082.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Table['Increased Sales'] = 0.05 * Table['Sales'] + Table['Sales']

,Date,ProductId,Product Type,Product,Sales,Profit,State,Area Code,Increased Sales
0,1/1/2010,1,Coffee,Amaretto,219,94,Colorado,719,229.95
1,1/1/2010,2,Coffee,Columbian,190,68,Colorado,970,199.50
2,1/1/2010,3,Coffee,Decaf Irish Cream,234,101,Colorado,970,245.70
3,1/1/2010,13,Tea,Green Tea,100,30,Colorado,303,105.00
4,1/1/2010,5,Espresso,Caffe Mocha,134,54,Colorado,303,140.70

In [36]:
##### 20. Find the maximum profit along with the product ID and product type.
T = Table.groupby(['ProductId','Product Type'])['Profit'].max().sort_values(ascending=False)
print(T.iloc[0:1])

ProductId  Product Type
2          Coffee          778
Name: Profit, dtype: int64

In [26]:
# 21. Create a function to fetch the result according to the product type
# from Product Table.
def get_products_by_type(Product, Product_Type):
    """Filter rows where Product_Type matches the parameter"""
    df = Product[Product['Product Type'] == Product_Type]
    return df

result = get_products_by_type(Product, 'Coffee')
print(result)

   ProductId Product Type            Product     Type
0          1       Coffee           Amaretto  Regular
1          2       Coffee          Columbian  Regular
2          3       Coffee  Decaf Irish Cream    Decaf

In [27]:
# #22. Write a function by creating a condition in which if the total expenses is less than
# 60 then it is a profit or else loss.
fact['Result'] = np.where(fact['Total Expenses'] < 60, 'Profit', 'Loss')
fact.head()

def profit_or_loss(tot_expense):
    if tot_expense < 60: 
        return "Profit"
    else:
        return "Loss"

fact['Result'] = fact['Total Expenses'].apply(profit_or_loss)
fact.head()

,Date,ProductId,Profit,Sales,Margin,COGS,Total Expenses,Marketing,Inventory,Budget Profit,Budget COGS,Budget Margin,Budget Sales,Area Code,Result
0,1/1/2010,1,94,219,130,89,36,24,777,100,90,130,220,719,Profit
1,1/1/2010,2,68,190,107,83,39,27,623,80,80,110,190,970,Profit
2,1/1/2010,3,101,234,139,95,38,26,821,110,100,140,240,970,Profit
3,1/1/2010,13,30,100,56,44,26,14,623,30,30,50,80,303,Profit
4,1/1/2010,5,54,134,80,54,26,15,456,70,60,90,150,303,Profit

In [28]:
# 23. Give the total weekly sales value with the date and product ID details. 

Table['week'] = pd.to_datetime(Table['Date']).dt.isocalendar().week
Table.columns
weekly_sales_per_productID = Table.groupby(['week','ProductId'])['Sales'].sum()
weekly_sales_per_productID.head()

####some advanced levels 
levels = ['week', 'Date', 'ProductId']
results = []

for i in range(len(levels), -1, -1):
    current_levels = levels[:i]
    if current_levels:
        grouped = Table.groupby(current_levels)['Sales'].sum().reset_index()
    else:
        # Grand Total layer
        grouped = pd.DataFrame([{'Sales': Table['Sales'].sum()}])
        
    results.append(grouped)

comb_table = pd.concat(results, ignore_index=True).sort_values(by=levels, na_position='last')
comb_table.head(20)

C:\Users\msi\AppData\Local\Temp\ipykernel_2200\1763571344.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Table['week'] = pd.to_datetime(Table['Date']).dt.isocalendar().week

     week      Date  ProductId  Sales
0       5  2/1/2010        1.0   1073
1       5  2/1/2010        2.0   4821
2       5  2/1/2010        3.0   2433
3       5  2/1/2010        4.0   1463
4       5  2/1/2010        5.0   3348
5       5  2/1/2010        6.0   3161
6       5  2/1/2010        7.0    988
7       5  2/1/2010        8.0   3016
8       5  2/1/2010        9.0   3613
9       5  2/1/2010       10.0   1417
10      5  2/1/2010       11.0   2879
11      5  2/1/2010       12.0   2596
12      5  2/1/2010       13.0   1284
312     5  2/1/2010        NaN  32092
13      5  2/1/2011        1.0   1144
14      5  2/1/2011        2.0   5135
15      5  2/1/2011        3.0   2593
16      5  2/1/2011        4.0   1559
17      5  2/1/2011        5.0   3566
18      5  2/1/2011        6.0   3368

In [37]:
# ###24. Apply union and intersection operator on the tables which consist of
# attribute area code.

union_df = pd.merge(fact, Location, on='Area Code', how='outer')

intersection_df = pd.merge(fact, Location, on='Area Code', how='inner')
print(union_df['Area Code'].head(2))
print("---------------------------------")
print(intersection_df['Area Code'].head(2))

0    203
1    203
Name: Area Code, dtype: int64
---------------------------------
0    707
1    845
Name: Area Code, dtype: int64

In [29]:
# ######25. Create a user-defined function for the product table to fetch a particular
# product type based upon the user’s preference.
def get_products_by_type(Product, Product_Type):
    """Filter rows where Product_Type matches the user preference"""
    df = Product[Product['Product Type'] == Product_Type]
    return df

result = get_products_by_type(Product, 'Coffee')
print(result)

   ProductId Product Type            Product     Type
0          1       Coffee           Amaretto  Regular
1          2       Coffee          Columbian  Regular
2          3       Coffee  Decaf Irish Cream    Decaf

In [30]:
#####26. Change the product type from coffee to tea where product ID is 1 and undo.
P = Product.loc[Product['ProductId'] == 1].copy()
Product.loc[Product['ProductId'] == 1, 'Product Type'] = 'tea'
print("After Change:\n", Product.head())
print("------------------------------------")
Product.loc[Product['ProductId'] == 1] = P
print("\nAfter Undo:\n", Product.head())

After Change:
    ProductId Product Type            Product     Type
0          1          tea           Amaretto  Regular
1          2       Coffee          Columbian  Regular
2          3       Coffee  Decaf Irish Cream    Decaf
3          4     Espresso        Caffe Latte  Regular
4          5     Espresso        Caffe Mocha  Regular
------------------------------------

After Undo:
    ProductId Product Type            Product     Type
0          1       Coffee           Amaretto  Regular
1          2       Coffee          Columbian  Regular
2          3       Coffee  Decaf Irish Cream    Decaf
3          4     Espresso        Caffe Latte  Regular
4          5     Espresso        Caffe Mocha  Regular

In [31]:
# 27. Display the date, product ID and sales where total expenses are
# between 100 to 200.

fact.head()
F = fact[(fact['Total Expenses'] > 100) & (fact['Total Expenses'] < 200)] 
F= F[['Date','ProductId','Sales']]
F.head()

        Date  ProductId  Sales
13  1/1/2010          5    546
25  1/1/2010          8    546
28  1/1/2010         12    546
48  1/1/2010          2    190
66  1/1/2010          5    190

In [32]:
### 28. Delete the records in the Product Table for regular type.
product_table = Product[Product['Product Type'] != 'regular']

product_table = Product.drop(Product[Product['Product Type'] == 'regular'].index)

print(product_table['Product Type'].unique())

['Coffee' 'Espresso' 'Herbal Tea' 'Tea']

In [33]:
#### 29. Display the ASCII value of the fifth character from the columnProduct.
valid_products = Product[Product['Product'].str.len() >= 5].copy()

valid_products['ascii_val'] = valid_products['Product'].str[4].apply(ord)

print(valid_products[['Product', 'ascii_val']])

              Product  ascii_val
0            Amaretto        101
1           Columbian        109
2   Decaf Irish Cream        102
3         Caffe Latte        101
4         Caffe Mocha        101
5      Decaf Espresso        102
6    Regular Espresso        108
7           Chamomile        111
8               Lemon        110
10         Darjeeling        101
11          Earl Grey         32
12          Green Tea        110